import type { SportAdventureHomeContent, SportAdventurePalette } from "@/lib/experiences/sportadventure/types";

export const sportAdventurePalette: SportAdventurePalette = {
  base: "#050505",
  panel: "rgba(12, 12, 12, 0.82)",
  panelAlt: "rgba(24, 24, 24, 0.78)",
  text: "#f3f1ec",
  muted: "rgba(243, 241, 236, 0.68)",
  line: "rgba(255, 255, 255, 0.12)",
  orange: "#ff6a00",
  lime: "#d5ff3f",
  red: "#c51632",
  white: "#ffffff",
};

export const sportAdventureHomePreset: SportAdventureHomeContent = {
  brand: "Sport Adventure",
  logoUrl: undefined,
  introEyebrow: "Motos · Indumentaria · Taller",
  introTitle: "SportAdventure",
  introHint: "",
  introActions: [{ label: "Catálogo", href: "/catalogo", variant: "primary" }],
  brandSections: [
    {
      id: "ktm",
      name: "KTM",
      eyebrow: "Orange",
      tagline: "Ready to race.",
      accent: "#ff5900",
      surface: "#160802",
      surfaceAlt: "#5a1c00",
      contrast: "#fff0e6",
      families: ["Enduro", "Adventure", "Naked"],
      placeholderLabel: "KTM",
    },
    {
      id: "husqvarna",
      name: "Husqvarna",
      eyebrow: "Blue",
      tagline: "Herencia sueca. Precisión.",
      accent: "#3b82f6",
      surface: "#050a12",
      surfaceAlt: "#0c2d6b",
      contrast: "#f0f6ff",
      families: ["Travel", "Enduro", "Street"],
      placeholderLabel: "Husqvarna",
      alignment: "right",
    },
    {
      id: "gasgas",
      name: "GasGas",
      eyebrow: "Red",
      tagline: "Pista y barro.",
      accent: "#e31837",
      surface: "#120103",
      surfaceAlt: "#6a0818",
      contrast: "#ffeef1",
      families: ["Motocross", "Trial", "Off-road"],
      placeholderLabel: "GasGas",
    },
    {
      id: "morini",
      name: "Morini",
      eyebrow: "Borgoña",
      tagline: "Carácter italiano.",
      accent: "#9b1f2e",
      surface: "#0c0407",
      surfaceAlt: "#3a0d14",
      contrast: "#f8e8ea",
      families: ["Adventure", "Scrambler", "Urban"],
      placeholderLabel: "Morini",
      alignment: "right",
    },
  ],
};
