import type { SportAdventureHomeContent, SportAdventurePalette } from "@/lib/experiences/sportadventure/types";

export const sportAdventurePalette: SportAdventurePalette = {
  base: "#050505",
  panel: "rgba(12, 12, 12, 0.82)",
  panelAlt: "rgba(24, 24, 24, 0.78)",
  text: "#f3f1ec",
  muted: "rgba(243, 241, 236, 0.68)",
  line: "rgba(255, 255, 255, 0.12)",
  orange: "#ff6a00",
  lime: "#d5ff3f",
  red: "#c51632",
  white: "#ffffff",
};

export const sportAdventureHomePreset: SportAdventureHomeContent = {
  brand: "Sport Adventure",
  // El logo real se inyecta desde bootstrap.branding.logoUrl en buildSportAdventureHomeContent.
  // URL oficial: https://dcdz4hoyp9hteums.public.blob.vercel-storage.com/shop-assets/69fbefceb403adf8b7df19ea/logo/1778717853790-317097715-127016313332066-549188438622822194-n.jpg
  logoUrl: undefined,
  introEyebrow: "Motos · Indumentaria · Repuestos · Taller",
  introTitle: "Sport Adventure",
  introHint: "Equipate para la próxima salida. Motos, indumentaria técnica, cascos, accesorios y repuestos en un solo lugar.",
  introActions: [
    { label: "Ver catálogo", href: "/catalogo", variant: "primary" },
    { label: "Ver indumentaria", href: "/catalogo?categoria=indumentaria", variant: "secondary" },
    { label: "Consultar por WhatsApp", href: "https://wa.me/5493416476751?text=Hola%2C+quiero+consultar+sobre+productos+de+Sport+Adventure.", variant: "ghost" },
  ],
  brandSections: [
    // ─── FEATURED ─────────────────────────────────────────────────────────────
    {
      id: "ktm",
      name: "KTM",
      eyebrow: "Orange",
      tagline: "Ready to race. La máquina de competición y aventura más reconocida del mundo.",
      accent: "#ff5900",
      surface: "#160802",
      surfaceAlt: "#5a1c00",
      contrast: "#fff0e6",
      families: ["Enduro", "Adventure", "Naked"],
      placeholderLabel: "KTM",
      featured: true,
      group: "Performance / Racing",
      uses: ["Racing", "Street", "Adventure", "Off-road"],
    },
    // ─── PERFORMANCE / RACING ────────────────────────────────────────────────
    {
      id: "husqvarna",
      name: "Husqvarna",
      eyebrow: "Pioneers",
      tagline: "Diseño sueco y rendimiento vanguardista para el asfalto y la tierra.",
      accent: "#f4d03f", // Yellow/Blue mix usually, sticking to yellow accent
      surface: "#0d0f12",
      surfaceAlt: "#1a1e24",
      contrast: "#f0f4f8",
      families: ["Norden", "Svartpilen", "Vitpilen", "Enduro"],
      placeholderLabel: "Husqvarna",
      group: "Performance / Racing",
      uses: ["Enduro", "Motocross", "Street", "Travel"],
    },
    {
      id: "gasgas",
      name: "GasGas",
      eyebrow: "Get on the gas",
      tagline: "Born to win. Pista, barro y adrenalina sin compromisos.",
      accent: "#e31837",
      surface: "#120103",
      surfaceAlt: "#6a0818",
      contrast: "#ffeef1",
      families: ["Motocross", "Trial", "Off-road"],
      placeholderLabel: "GasGas",
      group: "Performance / Racing",
      uses: ["Trial", "Enduro", "Motocross"],
    },
    {
      id: "aprilia",
      name: "Aprilia",
      eyebrow: "Be a racer",
      tagline: "ADN de competición y tecnología pura para dominar las calles y el circuito.",
      accent: "#ff0000",
      surface: "#111111",
      surfaceAlt: "#222222",
      contrast: "#ffffff",
      families: ["RS", "Tuono", "Tuareg"],
      placeholderLabel: "Aprilia",
      group: "Performance / Racing",
      uses: ["Track", "Sport", "Adventure"],
    },
    // ─── ADVENTURE / TOURING ──────────────────────────────────────────────────
    {
      id: "moto-morini",
      name: "Moto Morini",
      eyebrow: "Italian Heritage",
      tagline: "Espíritu aventurero y diseño italiano para explorar sin límites.",
      accent: "#d32f2f",
      surface: "#141010",
      surfaceAlt: "#2d1a1a",
      contrast: "#fdf5f5",
      families: ["X-Cape", "Seiemmezzo"],
      placeholderLabel: "Moto Morini",
      group: "Adventure / Touring",
      uses: ["Touring", "Adventure", "Scrambler"],
    },
    {
      id: "cfmoto",
      name: "CF Moto",
      eyebrow: "Experience More Together",
      tagline: "Innovación, tecnología y potencia para dominar cualquier terreno y distancia.",
      accent: "#0055a4",
      surface: "#0a1118",
      surfaceAlt: "#15263b",
      contrast: "#e6f0fa",
      families: ["MT", "NK", "SR", "CL-X"],
      placeholderLabel: "CF Moto",
      group: "Adventure / Touring",
      uses: ["Adventure", "Naked", "Sport"],
    },
    // ─── OFF-ROAD / CAMPO / UTILITY ───────────────────────────────────────────
    {
      id: "can-am",
      name: "Can-Am",
      eyebrow: "Off-Road",
      tagline: "Domination starts here. Rendimiento extremo y capacidad de trabajo en cualquier terreno.",
      accent: "#f0c400",
      surface: "#0a0900",
      surfaceAlt: "#3d3200",
      contrast: "#fffbe6",
      families: ["Outlander", "Maverick", "Defender", "Ryker"],
      placeholderLabel: "Can-Am",
      group: "Off-road / Campo / Utility",
      uses: ["ATV", "SSV", "Trabajo", "Aventura Extrema"],
      alignment: "right",
    },
    // ─── URBAN / LIFESTYLE ────────────────────────────────────────────────────
    {
      id: "royal-enfield",
      name: "Royal Enfield",
      eyebrow: "Heritage",
      tagline: "Pure motorcycling. Carácter clásico con alma de aventura para todos los días.",
      accent: "#c0392b",
      surface: "#0d0605",
      surfaceAlt: "#3b1209",
      contrast: "#f8e8e0",
      families: ["Himalayan", "Meteor", "Classic", "Interceptor"],
      placeholderLabel: "Royal Enfield",
      group: "Urban / Lifestyle",
      uses: ["Classic", "Cruiser", "Urban Adventure"],
      alignment: "right",
    },
    {
      id: "vespa",
      name: "Vespa",
      eyebrow: "La Dolce Vita",
      tagline: "El ícono atemporal del diseño italiano y la movilidad urbana elegante.",
      accent: "#8bc34a",
      surface: "#0a1205",
      surfaceAlt: "#1c330e",
      contrast: "#f1f8e9",
      families: ["Primavera", "Sprint", "GTS"],
      placeholderLabel: "Vespa",
      group: "Urban / Lifestyle",
      uses: ["Scooter", "Ciudad", "Lifestyle"],
    },
    {
      id: "piaggio",
      name: "Piaggio",
      eyebrow: "Move Beautifully",
      tagline: "Soluciones de movilidad inteligente y premium para la ciudad moderna.",
      accent: "#003b5c",
      surface: "#050f14",
      surfaceAlt: "#0d2836",
      contrast: "#e6f4fb",
      families: ["Beverly", "Liberty", "Medley", "MP3"],
      placeholderLabel: "Piaggio",
      group: "Urban / Lifestyle",
      uses: ["Urban Commuting", "Maxi Scooter", "3 Ruedas"],
    },
    {
      id: "qj-motor",
      name: "QJ Motor",
      eyebrow: "Riding to the Future",
      tagline: "Diseño moderno, tecnología accesible y versatilidad para el día a día.",
      accent: "#e63946",
      surface: "#140506",
      surfaceAlt: "#330d10",
      contrast: "#fdeced",
      families: ["SRV", "SRT", "SRK"],
      placeholderLabel: "QJ Motor",
      group: "Urban / Lifestyle",
      uses: ["Custom", "Street", "Urban Trail"],
    },
    // ─── ELÉCTRICAS / MOVILIDAD ───────────────────────────────────────────────
    {
      id: "super-soco",
      name: "Super Soco / VMoto",
      eyebrow: "Electric Evolution",
      tagline: "Silencio, eficiencia y diseño futurista. La nueva era de la movilidad eléctrica urbana.",
      accent: "#00e5ff",
      surface: "#001214",
      surfaceAlt: "#003238",
      contrast: "#e0fbff",
      families: ["TC Max", "CPX", "CUX"],
      placeholderLabel: "Super Soco",
      group: "Eléctricas / Movilidad",
      uses: ["100% Eléctrico", "Commuting", "Eco-friendly"],
    },
  ],
};
